vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "<leader>gp", ":Git -c push.default=current push<CR>")
vim.keymap.set("n", "<leader>gg", ":Git pull<CR>")
vim.keymap.set("n", "<leader>grs", ":Git reset --soft HEAD^<CR>")
vim.keymap.set("n", "<leader>gss", ":Git stash<CR>")
vim.keymap.set("n", "<leader>gsp", ":Git stash pop<CR>")
vim.keymap.set("n", "<leader>cbn", ":Git checkout -b feature/SER-")
vim.keymap.set("n", "<leader>cb", ":Git checkout -b ")
